{
 "title": "RET_panel",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Button",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Button No." }
   ],
   "targets": [
    {
     "alias": "ur_ros",
     "measurement": "RET_Logs_2022-03-25",
     "query": "SELECT \"button\" FROM \"RET_Logs\" WHERE (\"source\" = 'ur_ros') AND $timeFilter",
     "select": [
      [
       { "params": [ "button" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ur_ros" }
     ]
    },
    {
     "alias": "rpi",
     "measurement": "RET_Logs_2022-02-10",
     "query": "SELECT \"button\" FROM \"RET_Logs\" WHERE (\"source\" = 'rpi') AND $timeFilter",
     "select": [
      [
       { "params": [ "button" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "rpi" }
     ]
    },
    {
     "alias": "ur_native",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"button\" FROM \"RET_Logs\" WHERE (\"source\" = 'ur_native') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Btn 1 count - Robot",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "btn1_count_robot",
     "measurement": "RET_Logs",
     "query": "SELECT count(\"button\") FROM \"RET_Logs\" WHERE (\"button\"= 1 AND (\"source\" = 'ur_native' OR \"source\" = 'ur_ros' OR \"source\" = 'prbt')) AND $timeFilter",
     "select": [
      [
       { "params": [ "button" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ur_native" },
      { "condition": "OR", "key": "source", "operator": "=", "value": "ur_ros" },
      { "condition": "OR", "key": "source", "operator": "=", "value": "prbt" }
     ]
    }
   ]
  },
  {
   "title": "Btn 1 count - RPI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RET_Logs_2022-03-23",
     "query": "SELECT count(\"button\") FROM \"RET_Logs\" WHERE (\"button\" = 1 AND (\"source\" = 'rpi') ) AND $timeFilter",
     "select": [
      [
       { "params": [ "button" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ur_native" }
     ]
    }
   ]
  },
  {
   "title": "Btn 2 count - Robot",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RET_Logs_2022-03-23",
     "query": "SELECT count(\"button\") FROM \"RET_Logs\" WHERE (\"button\" = 2 AND (\"source\" = 'ur_ros' OR \"source\" = 'ur_native' OR \"source\" = 'prbt')) AND $timeFilter",
     "select": [
      [
       { "params": [ "button" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ur_native" }
     ]
    }
   ]
  },
  {
   "title": "Btn 2 count - RPI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RET_Logs_2022-03-23",
     "query": "SELECT count(\"button\") FROM \"RET_Logs\" WHERE (\"button\" = 2 AND (\"source\" = 'rpi'))  AND $timeFilter",
     "select": [
      [
       { "params": [ "button" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ur_native" }
     ]
    }
   ]
  },
  { "title": "Event", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latest Event",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "limit": 10,
     "measurement": "RET_Events_2022-03-23",
     "query": "SELECT \"description\" FROM \"RET_Events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "description" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeout Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "limit": 10,
     "measurement": "RET_Events_2022-03-23",
     "query": "SELECT count(\"description\") FROM \"RET_Events\" WHERE (\"type\" = 'confimration_timeout') AND $timeFilter LIMIT 10",
     "select": [
      [
       { "params": [ "description" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "confimration_timeout" }
     ]
    }
   ]
  },
  {
   "title": "Mismatch count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "limit": 10,
     "measurement": "RET_Events_2022-03-23",
     "query": "SELECT count(\"description\") FROM \"RET_Events\" WHERE (\"type\" = 'confirmation_mismatch') AND $timeFilter LIMIT 10",
     "select": [
      [
       { "params": [ "description" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "confirmation_mismatch" }
     ]
    }
   ]
  },
  {
   "title": "Event list",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "RET_Events",
     "query": "SELECT \"description\", \"type\" FROM \"RET_Events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "confimration_timeout" }
     ]
    }
   ]
  }
 ]
}